### ISSUE TITLE
Implementar usuarios y autenticación

### ISSUE THREAD

**Issue by thiagocabrera** [sklarmatias/tacs-grupo-3#11]

**Comment by thiagocabrera** [comment]
![image](https://github.com/sklarmatias/tacs-grupo-3/assets/82061778/15d08c3e-c297-4af2-b297-cdfa3c590c5d)
Punto 1

**Comment by thiagocabrera** [comment]
La fácil: mandar API Key en el header de cada request.
Implementar Middleware

**Comment by matiasmagarzo** [comment]
Ya esta hecho el login de usuario, faltaria encriptar la clave en el bot cuando el usuario ingresa asi se envia encriptada a api y no en texto plano.

**Comment by matiasmagarzo** [comment]
Mas adelante habria se podria la api key, seria una palabra encriptada que se guardaria en una variable de entorno en api y el bot y se envia en el header.
