### ISSUE TITLE
Validacion de los inputs en el bot

### ISSUE THREAD

**Issue by matiasmagarzo** [sklarmatias/tacs-grupo-3#12]
En el caso de que el input sea invalido volver a pedir el mismo dato. Para el alta de articulo y para los menus de mostrar articulo.

**Comment by matiasmagarzo** [comment]
Implementar el teclado de telegram para donde necesitemos un input donde tenemos que solo permitir determinadas opciones. Yo le puse en el mensaje las opciones disponibles para esos casos por el momento.

**Comment by thiagocabrera** [comment]
OBTENER ARTICULOS: mostrar el estado actual.
Acción cerrar artículos: que valide que el ingresado no esté cerrado.
Acción suscribirse: que valide que el ingresado no esté cerrado ni completo.

En el crear:
validar que la deadline sea futura.

El registrarme:
loguear usuario
